from enum import Enum, auto
#CONSTANTS
HEIGHT = 800
WIDTH = 1200
MAIN_GRAPH_OFFSET = 0.01
MAIN_GRAPH_HEIGHT = 1-(2*MAIN_GRAPH_OFFSET)
MAIN_GRAPH_WIDTH = 0.7-(2*MAIN_GRAPH_OFFSET)
CHOOSE_RANDOM_HEIGHT = (MAIN_GRAPH_HEIGHT - 4*MAIN_GRAPH_OFFSET)/13
CHOOSE_RANDOM_WIDTH = 1 - (MAIN_GRAPH_WIDTH + 3*MAIN_GRAPH_OFFSET)
LOADING_STEPS_HEIGHT = CHOOSE_RANDOM_HEIGHT
LOADING_STEPS_WIDTH = CHOOSE_RANDOM_WIDTH
CHOOSE_PRODUCTION_HEIGHT = 3 * LOADING_STEPS_HEIGHT
CHOOSE_PRODUCTION_WIDTH = LOADING_STEPS_WIDTH
ACTION_LOG_HEIGHT = 4*CHOOSE_RANDOM_HEIGHT
ACTION_LOG_WIDTH = LOADING_STEPS_WIDTH
STATISTICS_HEIGHT = ACTION_LOG_HEIGHT
STATISTICS_WIDTH = LOADING_STEPS_WIDTH

TITLE_COLOR = '#a3ba9c'
TITLE_FONT = ("Calibri Light", 12)
OUTPUT_FONT = ("Calibri Light", 12)
INPUT_FONT = ("Calibri Light", 12)

class ProgramStatus(Enum):
    CURRENT = auto()
    HISTORY = auto()