#CONSTANTS
HEIGHT = 700
WIDTH = 1000
MAIN_GRAPH_OFFSET = 0.02
MAIN_GRAPH_HEIGHT = 1-(2*MAIN_GRAPH_OFFSET)
MAIN_GRAPH_WIDTH = 0.7-(2*MAIN_GRAPH_OFFSET)
LOADING_STEPS_HEIGHT = (MAIN_GRAPH_HEIGHT - 2*MAIN_GRAPH_OFFSET)/5
LOADING_STEPS_WIDTH = 1 - (MAIN_GRAPH_WIDTH + 3*MAIN_GRAPH_OFFSET)
ACTION_LOG_HEIGHT = 2*LOADING_STEPS_HEIGHT
ACTION_LOG_WIDTH = LOADING_STEPS_WIDTH
STATISTICS_HEIGHT = 2*LOADING_STEPS_HEIGHT
STATISTICS_WIDTH = LOADING_STEPS_WIDTH